### ISSUE TITLE
iPhoneX屏幕安全区问题

### ISSUE THREAD

**Issue by square-li** [LofOWL/QueensU#2]
Hello！
在iPhoneX等全面屏上面那两个上下翻页的按钮过小并过于接近屏幕底端，并不是很好操作。可以参考[iOS设计指南](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/)和[微信小程序设计指南](https://developers.weixin.qq.com/miniprogram/design/#%E5%87%8F%E5%B0%91%E8%BE%93%E5%85%A5)

**Comment by LofOWL** [comment]
学长您好！
请问方便加微信联系吗？
我微信是
Jeffersonjjin
